name: Analysis

on:
    push:
        branches:
            - main
            - '*.x'
    pull_request:
    schedule:
        -   cron: '0 5 * * *'

jobs:
    static-analysis:
        name: "Rund static analysis with P${{ matrix.php }} , L${{ matrix.laravel }} and ${{ matrix.dependency-version }} dependencies"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                    - "8.4"
                laravel:
                    - "^12.0"
                    - "^11.0"
                    - "^10.0"
                dependency-version:
                    - "lowest"
                    - "highest"
                include:
                    -   laravel: "^12.0"
                        testbench: 10.*
                    -   laravel: "^11.0"
                        testbench: 9.*
                    -   laravel: "^10.0"
                        testbench: 8.*
                exclude:
                    -   laravel: "^12.0"
                        php: 8.1
                    -   laravel: "^11.0"
                        php: 8.1
        steps:
            -   uses: "actions/checkout@v4"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            -   name: Run PHPStan
                run: ./vendor/bin/phpstan analyse --error-format=github --configuration="./dev/config/phpstan.neon"

    insights:
        name: "Check insights with P${{ matrix.php }} , L${{ matrix.laravel }} and ${{ matrix.dependency-version }} dependencies"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php:
                    - "8.4"
                laravel:
                    - "^12.0"
                dependency-version:
                    - "highest"
                include:
                    -   laravel: "^12.0"
                        testbench: 10.*
        steps:
            -   uses: "actions/checkout@v4"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            -   name: Run PHPInsights
                run: ./vendor/bin/phpinsights --no-interaction --config-path="./dev/config/phpinsights.php" analyse

    format:
        name: "Check format with P${{ matrix.php }} , L${{ matrix.laravel }} and ${{ matrix.dependency-version }} dependencies"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php:
                    - "8.4"
                laravel:
                    - "^12.0"
                dependency-version:
                    - "highest"
                include:
                    -   laravel: "^12.0"
                        testbench: 10.*
        steps:
            -   uses: "actions/checkout@v4"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            -   name: Run PHP-CS-Fixer
                run: ./vendor/bin/php-cs-fixer check --config="./dev/config/php-cs-fixer.php"

    markdown:
        name: "Lint markdown files"
        runs-on: ubuntu-latest
        steps:
            -   uses: "actions/checkout@v4"
            -   uses: DavidAnson/markdownlint-cli2-action@v19
                with:
                    config: 'dev/config/.markdownlint.jsonc'
                    globs: |
                        **/*.md
                        !CHANGELOG.md
