name: Tests

on:
    push:
        branches:
            - main
            - '*.x'
    pull_request:
    schedule:
        -   cron: '0 5 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    define_matrix:
        runs-on: ubuntu-latest
        outputs:
            php: ${{ steps.php.outputs.php }}
            laravel: ${{ steps.laravel.outputs.laravel }}
            dependency: ${{ steps.dependency.outputs.dependency }}
            excludes: ${{ steps.excludes.outputs.excludes }}
        steps:
            -   name: Define PHP Versions
                id: php
                run: |
                    echo 'php=["8.5", "8.4", "8.3", "8.2"]' >> "$GITHUB_OUTPUT"
            -   name: Define Laravel Versions
                id: laravel
                run: |
                    echo 'laravel=["13.*", "12.*", "11.*"]' >> "$GITHUB_OUTPUT"
            -   name: Define Dependency Levels
                id: dependency
                run: |
                    echo 'dependency=["prefer-lowest", "prefer-stable"]' >> "$GITHUB_OUTPUT"
            -   name: Define Excludes
                id: excludes
                run: |
                    echo 'excludes=[{"php":"8.2","laravel":"13.*"}]' >> "$GITHUB_OUTPUT"
    unit_test:
        name: "Unit-Testing with P${{ matrix.php }} , L${{ matrix.laravel }} and ${{ matrix.dependency }} dependencies"
        needs:
            - define_matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: ${{ fromJson(needs.define_matrix.outputs.php) }}
                laravel: ${{ fromJson(needs.define_matrix.outputs.laravel) }}
                dependency: ${{ fromJson(needs.define_matrix.outputs.dependency) }}
                exclude: ${{ fromJson(needs.define_matrix.outputs.excludes) }}
                include:
                    -   laravel: "13.*"
                        testbench: 11.*
                    -   laravel: "12.*"
                        testbench: 10.*
                    -   laravel: "11.*"
                        testbench: 9.*
        steps:
            -   uses: "actions/checkout@v4"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: xdebug
            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency }} --prefer-dist --no-interaction
            -   name: Tests
                run: ./vendor/bin/pest --coverage --parallel ./tests/Unit
            -   name: 'Upload Artifact'
                uses: actions/upload-artifact@v4
                with:
                    name: "coverage-reports-unit-${{ matrix.php }}-${{ matrix.dependencies }}"
                    path: |
                        tests/test_results/clover.xml
                        tests/test_results/cobertura.xml
                        tests/test_results/coverage.txt
                    retention-days: 2
    component_test:
        name: "Component-Testing with P${{ matrix.php }} , L${{ matrix.laravel }} and ${{ matrix.dependency }} dependencies"
        needs:
            - define_matrix
            - unit_test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: ${{ fromJson(needs.define_matrix.outputs.php) }}
                laravel: ${{ fromJson(needs.define_matrix.outputs.laravel) }}
                dependency: ${{ fromJson(needs.define_matrix.outputs.dependency) }}
                exclude: ${{ fromJson(needs.define_matrix.outputs.excludes) }}
                include:
                    -   laravel: "13.*"
                        testbench: 11.*
                    -   laravel: "12.*"
                        testbench: 10.*
                    -   laravel: "11.*"
                        testbench: 9.*
        steps:
            -   uses: "actions/checkout@v4"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: xdebug
            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency }} --prefer-dist --no-interaction
            -   name: Tests
                run: ./vendor/bin/pest --coverage --parallel ./tests/Component
            -   name: 'Upload Artifact'
                uses: actions/upload-artifact@v4
                with:
                    name: "coverage-reports-component-${{ matrix.php }}-${{ matrix.dependencies }}"
                    path: |
                        tests/test_results/clover.xml
                        tests/test_results/cobertura.xml
                        tests/test_results/coverage.txt
                    retention-days: 2
